### ISSUE TITLE
socks4/5 Proxy and find out the public IP of my container

### ISSUE THREAD

**Issue by shahram7** [P3TERX/Aria2-Pro-Docker#128]
Hi there,

due to lack of the SOCKS4/5 Proxies feature , I have routed the traffic of my docker container to another container ([gluetun](https://github.com/qdm12/gluetun/wiki)) which is connected to a VPN.
First I have entered the network-mode: container:gluetun for both ariang and aria2pro services but I had problem to call the ariang
now my stack looks like this:

```
version: "3.8"

services:

  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - RPC_SECRET=P3TERX
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Europe/Berlin
    volumes:
      - config:/config
      - /nas/NAS/download:/downloads
    network_mode: container:gluetun

    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    network_mode: bridge
    ports:
      - 6880:6880 #aria-ng
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
volumes:
  config:
```

And now when I run aria-ng it says that aria2 is disconnected!

I would like to check the public IP of the container too.
I have added the curl with "apk add curl"
but I don't receive anything back with "curl -s ifconfig.me"
![image](https://github.com/P3TERX/Aria2-Pro-Docker/assets/34509793/43df0973-8e46-4ac6-b170-d593216918d2)
And I was not able to install bind-tools 
"bind-tools (no such package)"
Could you guys help me further?

Best regards, Shahram
