### ISSUE TITLE
关于docker部署问题

### ISSUE THREAD

**Issue by MuXia-0326** [P3TERX/Aria2-Pro-Docker#133]
使用下面的`docker-compose.yml`文件部署的ariang 无法通过docker网络的别名连接上aria2

![image](https://github.com/P3TERX/Aria2-Pro-Docker/assets/63834850/c821ef30-df25-48ae-a228-c76ed4cddb58)

```yml
version: "3.8"

services:

  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - RPC_SECRET=mo
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=false
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ${PWD}/aria2-config:/config
      - ${PWD}/aria2-downloads:/downloads
    networks:
      net_clash:
        aliases:
          - aria2
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    networks:
      net_clash:
        aliases:
          - ariang
    ports:
      - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

networks: 
  net_clash: 
    external: true
```
