### ISSUE TITLE
Can not connect to Aria2-pro using docker

### ISSUE THREAD

**Issue by Georgebobby** [P3TERX/Aria2-Pro-Docker#144]
I'm on Ubuntu 22.04 LTS and have opened up the corresponding port and cleared all firewall rules `sudo iptables -F` (ufw is disabled). However, I just can't connect to aria2-pro container. when setting up in Ariang, I tried to connect to http://aria-E5:6881/jsonrpc with mypassword but it just shows "not connected". I have no clue why. 
The following is my docker compose file:
```
version: "3.8"
services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    ports:
      - "5212:5212"
    volumes:
      - temp_data:/data
      - ./cloudreve/uploads:/cloudreve/uploads
      - ./cloudreve/conf.ini:/cloudreve/conf.ini
      - ./cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - ./cloudreve/avatar:/cloudreve/avatar
    depends_on:
      - aria2-TH
      - aria2-E5
      - aria2-willywang8216
    networks:
      - network_cr
  ariang:
    image: p3terx/ariang
    container_name: ariang
    restart: unless-stopped
    command: --port 6880 --ipv6
    logging:
      driver: json-file
      options:
        max-size: 1m
    ports:
      - "6880:6880"
    networks:
      - network_cr
  aria2-E5:
    container_name: aria2-E5
    image: p3terx/aria2-pro
    restart: unless-stopped
    ports:
      - 6888:6888
        #DHT listen port
      - 6888:6888/udp
        # BT listen port 
      - 6881:6881
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=P3TERX
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - SPECIAL_MODE=rclone
      - RPC_SECRET="mypassword"
      - RPC_PORT=6881
      - TZ=Asia/Taipei
    volumes:
      - ./aria2-E5/config:/config
      - ~/rclone-E5-downloads:/downloads
      - temp_data:/data
    networks:
      - network_cr
networks:
  network_cr:
    driver: bridge
    external: true
volumes:
  temp_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind
```
