### ISSUE TITLE
ariang can not connect to aria2 by using name in docker-compose

### ISSUE THREAD

**Issue by rickywei** [P3TERX/Aria2-Pro-Docker#153]
docker-compose.yaml

```yml
version: "3.5"

services:
  aria2-pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - RPC_SECRET=P3TERX
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ./data/aria2/aria2-config:/config
      - /HDD/WD/aria:/downloads
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

  ariang:
    container_name: ariang
    image: p3terx/ariang
    user: 1000:1000
    ports:
     - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
```

![image](https://github.com/P3TERX/Aria2-Pro-Docker/assets/22569611/e1097c4e-04a0-4dce-8795-a677252865a1)
