### ISSUE TITLE
ariang restart all the time when implemented it on raspberrypi4b

### ISSUE THREAD

**Issue by wswv** [P3TERX/Aria2-Pro-Docker#32]
Due to there is no more log, so I can't provide more detail about it. if you know how to get more log from it, I'm glad to try it again, thanks!

The docker-compose.yaml come from your sample and no change for itself.
```

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    network_mode: host
#    network_mode: bridge
#    ports:
#      - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

```
