### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by nishant2019** [P3TERX/Aria2-Pro-Docker#56]
I have successfully installed the software using docker on raspberry pi. However when a open the webpage I get Authorization Error. I have attached the picture for reference

![image](https://user-images.githubusercontent.com/49723167/134609447-4b3eb58a-318e-423f-9ce9-81a2d771623f.png)

**Comment by ans-** [comment]
same issue

**Comment by noxxxxxxxx** [comment]
@nishant2019 @dbinheaven @ans- 

Here is the solution, if you use docker-compose

```bash
version: "3.8"

services:

  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    volumes:
      - ${PWD}/config:/config
      - ${PWD}/downloads:/downloads
   .........
```


you will find `config` folder

```
cat config/aria2.conf
# find 👇
# RPC 密钥
rpc-secret=P3TERX
```

copy the `rpc-secret` value `P3TERX`

![截屏2021-10-30 20 48 40](https://user-images.githubusercontent.com/37919656/139533459-db733deb-1aba-4d4a-837f-1357ec8b93cc.png)

**Comment by KourosZanbouri** [comment]
is it possible to add web authentication through AriaNg? I mean for the page... ( because anyone with the IP and port can access)

**Comment by fragolinux** [comment]
hi, is this "browser" related? i mean, i've this dockerfile:

```
version: "3.8"

services:

  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=P3TERX
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Europe/Rome
    volumes:
      - ${PWD}/aria2-config:/config
      - ${PWD}/aria2-downloads:/downloads
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
    network_mode: host
#    network_mode: bridge
#    ports:
#      - 6800:6800
#      - 6888:6888
#      - 6888:6888/udp
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    network_mode: host
#    network_mode: bridge
#    ports:
#      - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
```

and this aria2.conf:

```
dir=/downloads
disk-cache=64M
file-allocation=falloc
no-file-allocation-limit=64M
continue=true
always-resume=false
max-resume-failure-tries=0
remote-time=true
input-file=/config/aria2.session
save-session=/config/aria2.session
save-session-interval=1
auto-save-interval=20
force-save=false
max-file-not-found=10
max-tries=0
retry-wait=10
connect-timeout=10
timeout=10
max-concurrent-downloads=5
max-connection-per-server=32
split=64
min-split-size=4M
piece-length=1M
allow-piece-length-change=true
lowest-speed-limit=0
max-overall-download-limit=0
max-download-limit=0
disable-ipv6=true
http-accept-gzip=true
reuse-uri=false
no-netrc=true
allow-overwrite=false
auto-file-renaming=true
content-disposition-default-utf8=true
listen-port=6888
dht-listen-port=6888
enable-dht=true
enable-dht6=false
dht-file-path=/config/dht.dat
dht-file-path6=/config/dht6.dat
dht-entry-point=dht.transmissionbt.com:6881
dht-entry-point6=dht.transmissionbt.com:6881
bt-enable-lpd=true
enable-peer-exchange=true
bt-max-peers=128
bt-request-peer-speed-limit=10M
max-overall-upload-limit=2M
max-upload-limit=0
seed-ratio=1.0
seed-time=0
bt-hash-check-seed=true
bt-seed-unverified=false
bt-tracker-connect-timeout=10
bt-tracker-timeout=10
bt-prioritize-piece=head=32M,tail=32M
rpc-save-upload-metadata=true
follow-torrent=true
pause-metadata=false
bt-save-metadata=true
bt-load-saved-metadata=true
bt-remove-unselected-file=true
bt-force-encryption=true
bt-detach-seed-only=true
user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.47
peer-agent=Deluge 1.3.15
peer-id-prefix=-DE13F0-
on-download-stop=/config/script/delete.sh
on-download-complete=/config/script/clean.sh
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-secret=P3TERX
rpc-max-request-size=10M
console-log-level=notice
quiet=false
summary-interval=0
retry-on-400=true
retry-on-403=true
retry-on-406=true
retry-on-unknown=true
bt-tracker=
```

but if i open a new anonymous browser session (or i change browser, or pc), the error pops up again, and i need to add the secret explicitely again in the web gui, like the one in the config file is ignored...
