### ISSUE TITLE
[问题]如何调整 ariang 中 rpc host

### ISSUE THREAD

**Issue by whg517** [P3TERX/Aria2-Pro-Docker#98]
你好，当我在使用你提供的 docker-compose 时，我发现 host 网络下无法正常使用。我的使用实践时应用容器在子网下面，同时暴露端口。但是当我调整网络后，发现我无法调整 ariang 容器中的 Aria2 地址，它默认是 `http://127.0.0.1:6800/jsonrpc` ，我想通过 docker-compose 指定 Aria2-Pro 容器的主机名，让 ariang 容器通过主机名访问 aria2 服务。

一下为我的 docker-compose 

```yml
version: "3.8"

services:

  aria2pro:
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=P3TERX
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ${PWD}/aria2-config:/config
      - ${PWD}/aria2-downloads:/downloads
    networks:
      - app
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: 1

  ariang:
    image: p3terx/ariang
    command: 
      - --port 6880
      - -ipv6
    networks:
      - app
    ports:
      - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: 1

networks:
  app:
    external: true
    name: app

```

如上文件，我如何能将  `aria2pro` 容器的主机名传递到 `ariang` 里面，并将 `ariang` 到 rpc host 调整。

---

另外我一直没有找到 [p3terx/ariang](https://hub.docker.com/r/p3terx/ariang) 容器的构建仓库在哪里，也没有找到构建该容器的 Dockerfile 是怎么写的，可否将内容附在容器的 README 中？
